//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantoofaceServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tutorial
    {
        public int ID { get; set; }
        public Nullable<int> catId { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual Tbl_Application Tbl_Application { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
